<?php
/**
 * Generated by Haxe 4.0.0
 */

namespace _Array;

use \php\_Boot\HxClosure;
use \php\Boot;

class ArrayIterator {
	/**
	 * @var \Array_hx
	 */
	public $arr;
	/**
	 * @var int
	 */
	public $idx;


	/**
	 * @param \Array_hx $arr
	 * 
	 * @return void
	 */
	public function __construct ($arr) {
		#/usr/share/haxe/std/php7/_std/Array.hx:213: characters 2-16
		$this->arr = $arr;
		#/usr/share/haxe/std/php7/_std/Array.hx:214: characters 2-9
		$this->idx = 0;
	}


	/**
	 * @param string $method
	 * 
	 * @return HxClosure
	 */
	public function __get ($method) {
		#/usr/share/haxe/std/php7/_std/Array.hx:228: lines 228-231
		switch ($method) {
			case "hasNext":
			case "next":
				#/usr/share/haxe/std/php7/_std/Array.hx:229: characters 27-53
				return new HxClosure($this, $method);
				break;
			default:
				#/usr/share/haxe/std/php7/_std/Array.hx:230: characters 11-15
				return null;
				break;
		}
	}


	/**
	 * @return bool
	 */
	public function hasNext () {
		#/usr/share/haxe/std/php7/_std/Array.hx:218: characters 2-25
		return $this->idx < $this->arr->length;
	}


	/**
	 * @return mixed
	 */
	public function next () {
		#/usr/share/haxe/std/php7/_std/Array.hx:222: characters 2-19
		return ($this->arr->arr[$this->idx++] ?? null);
	}
}


Boot::registerClass(ArrayIterator::class, '_Array.ArrayIterator');
