<?php
/**
 * Generated by Haxe 4.0.0
 */

namespace haxe\ds;

use \haxe\IMap;
use \php\Boot;
use \php\_NativeArray\NativeArrayIterator;

class StringMap implements IMap {
	/**
	 * @var mixed
	 */
	public $data;


	/**
	 * @return void
	 */
	public function __construct () {
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:34: characters 9-31
		$this1 = [];
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:34: characters 2-31
		$this->data = $this1;
	}


	/**
	 * @param string $key
	 * 
	 * @return bool
	 */
	public function exists ($key) {
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:46: characters 2-43
		return array_key_exists($key, $this->data);
	}


	/**
	 * @param string $key
	 * 
	 * @return mixed
	 */
	public function get ($key) {
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:42: characters 2-44
		return ($this->data[$key] ?? null);
	}


	/**
	 * @return object
	 */
	public function iterator () {
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:63: characters 9-24
		return new NativeArrayIterator($this->data);
	}


	/**
	 * @return object
	 */
	public function keys () {
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:59: characters 9-71
		return new NativeArrayIterator(array_map("strval", array_keys($this->data)));
	}


	/**
	 * @param string $key
	 * 
	 * @return bool
	 */
	public function remove ($key) {
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:50: lines 50-55
		if (array_key_exists($key, $this->data)) {
			#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:51: characters 3-26
			unset($this->data[$key]);
			#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:52: characters 3-14
			return true;
		} else {
			#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:54: characters 3-15
			return false;
		}
	}


	/**
	 * @param string $key
	 * @param mixed $value
	 * 
	 * @return void
	 */
	public function set ($key, $value) {
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:38: characters 2-19
		$this->data[$key] = $value;
	}


	/**
	 * @return string
	 */
	public function toString () {
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:67: characters 14-31
		$this1 = [];
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:67: characters 2-32
		$parts = $this1;
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:68: lines 68-70
		foreach (($this->data) as $key => $value) {
			#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:69: characters 28-58
			$tmp = "" . ($key??'null') . " => " . (\Std::string($value)??'null');
			#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:69: characters 3-59
			array_push($parts, $tmp);
		};
		#/usr/share/haxe/std/php7/_std/haxe/ds/StringMap.hx:72: characters 2-48
		return "{" . (implode(", ", $parts)??'null') . "}";
	}


	public function __toString() {
		return $this->toString();
	}
}


Boot::registerClass(StringMap::class, 'haxe.ds.StringMap');
