<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace persistence\_Persistence;

use \php\_Boot\HxAnon;
use \php\Boot;
use \haxe\Exception;
use \php\_Boot\HxClosure;

/**
 * Getter
 */
class Getter {

	/**
	 * @var mixed
	 */
	public $queryMapper;
	/**
	 * @var string
	 */
	public $recordType;
	/**
	 * @var mixed
	 */
	public $resultMapper;
	/**
	 * @var mixed
	 */
	public $strategyMethod;
	/**
	 * @var bool
	 */
	public $useQueryValuesAsParams;

	/**
	 * @param string $recordType
	 * @param mixed $strategyMethod
	 * @param mixed $queryMapper
	 * @param mixed $resultMapper
	 * @param bool $useQueryValuesAsParams
	 * 
	 * @return void
	 */
	public function __construct ($recordType, $strategyMethod, $queryMapper, $resultMapper, $useQueryValuesAsParams) {
		#/src/persistence/Persistence.hx:341: characters 7-77
		$tmp = null;
		if (!is_string($strategyMethod)) {
			#/src/persistence/Persistence.hx:341: characters 43-77
			$f = $strategyMethod;
			#/src/persistence/Persistence.hx:341: characters 7-77
			$tmp = !(($f instanceof \Closure) || ($f instanceof HxClosure));
		} else {
			$tmp = false;
		}
		#/src/persistence/Persistence.hx:341: lines 341-343
		if ($tmp) {
			#/src/persistence/Persistence.hx:342: characters 4-9
			throw Exception::thrown("strategyMethod must be a string or function");
		}
		#/src/persistence/Persistence.hx:344: characters 7-71
		$tmp = null;
		if (!is_string($queryMapper)) {
			#/src/persistence/Persistence.hx:344: characters 40-71
			$f = $queryMapper;
			#/src/persistence/Persistence.hx:344: characters 7-71
			$tmp = !(($f instanceof \Closure) || ($f instanceof HxClosure));
		} else {
			$tmp = false;
		}
		#/src/persistence/Persistence.hx:344: lines 344-346
		if ($tmp) {
			#/src/persistence/Persistence.hx:345: characters 4-9
			throw Exception::thrown("queryMapper must be a string or function");
		}
		#/src/persistence/Persistence.hx:347: characters 7-73
		$tmp = null;
		if (!is_string($resultMapper)) {
			#/src/persistence/Persistence.hx:347: characters 41-73
			$f = $resultMapper;
			#/src/persistence/Persistence.hx:347: characters 7-73
			$tmp = !(($f instanceof \Closure) || ($f instanceof HxClosure));
		} else {
			$tmp = false;
		}
		#/src/persistence/Persistence.hx:347: lines 347-349
		if ($tmp) {
			#/src/persistence/Persistence.hx:348: characters 4-9
			throw Exception::thrown("resultMapper must be a string or function");
		}
		#/src/persistence/Persistence.hx:350: characters 3-31
		$this->recordType = $recordType;
		#/src/persistence/Persistence.hx:351: characters 3-39
		$this->strategyMethod = $strategyMethod;
		#/src/persistence/Persistence.hx:352: characters 3-33
		$this->queryMapper = $queryMapper;
		#/src/persistence/Persistence.hx:353: characters 3-35
		$this->resultMapper = $resultMapper;
		#/src/persistence/Persistence.hx:354: characters 3-55
		$this->useQueryValuesAsParams = $useQueryValuesAsParams;
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


	}
}

Boot::registerClass(Getter::class, 'persistence._Persistence.Getter');
Boot::registerMeta(Getter::class, new HxAnon(["obj" => new HxAnon(["SuppressWarnings" => \Array_hx::wrap(["checkstyle:FieldDocComment"])])]));
Getter::__hx__init();
