<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace persistence\_Persistence;

use \php\_Boot\HxAnon;
use \php\Boot;
use \haxe\Exception;
use \php\_Boot\HxClosure;

/**
 * Mutator
 */
class Mutator {

	/**
	 * @var string
	 */
	public $recordType;
	/**
	 * @var mixed
	 */
	public $strategyMethod;
	/**
	 * @var mixed
	 */
	public $updateMapper;

	/**
	 * @param string $recordType
	 * @param mixed $strategyMethod
	 * @param mixed $updateMapper
	 * 
	 * @return void
	 */
	public function __construct ($recordType, $strategyMethod, $updateMapper) {
		#/src/persistence/Persistence.hx:179: characters 7-77
		$tmp = null;
		if (!is_string($strategyMethod)) {
			#/src/persistence/Persistence.hx:179: characters 43-77
			$f = $strategyMethod;
			#/src/persistence/Persistence.hx:179: characters 7-77
			$tmp = !(($f instanceof \Closure) || ($f instanceof HxClosure));
		} else {
			$tmp = false;
		}
		#/src/persistence/Persistence.hx:179: lines 179-181
		if ($tmp) {
			#/src/persistence/Persistence.hx:180: characters 4-9
			throw Exception::thrown("strategyMethod must be a string or function");
		}
		#/src/persistence/Persistence.hx:182: characters 7-73
		$tmp = null;
		if (!is_string($updateMapper)) {
			#/src/persistence/Persistence.hx:182: characters 41-73
			$f = $updateMapper;
			#/src/persistence/Persistence.hx:182: characters 7-73
			$tmp = !(($f instanceof \Closure) || ($f instanceof HxClosure));
		} else {
			$tmp = false;
		}
		#/src/persistence/Persistence.hx:182: lines 182-184
		if ($tmp) {
			#/src/persistence/Persistence.hx:183: characters 4-9
			throw Exception::thrown("updateMapper must be a string or function");
		}
		#/src/persistence/Persistence.hx:185: characters 3-31
		$this->recordType = $recordType;
		#/src/persistence/Persistence.hx:186: characters 3-39
		$this->strategyMethod = $strategyMethod;
		#/src/persistence/Persistence.hx:187: characters 3-35
		$this->updateMapper = $updateMapper;
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


	}
}

Boot::registerClass(Mutator::class, 'persistence._Persistence.Mutator');
Boot::registerMeta(Mutator::class, new HxAnon(["obj" => new HxAnon(["SuppressWarnings" => \Array_hx::wrap(["checkstyle:FieldDocComment"])])]));
Mutator::__hx__init();
