<?php
/**
 * Generated by Haxe 4.0.0
 */

namespace php\_NativeIndexedArray;

use \php\Boot;

final class NativeIndexedArray_Impl_ {
	/**
	 * @return mixed
	 */
	static public function _new () {
		#/usr/share/haxe/std/php7/NativeIndexedArray.hx:26: character 15
		$this1 = [];
		#/usr/share/haxe/std/php7/NativeIndexedArray.hx:26: character 15
		return $this1;
	}


	/**
	 * @param \Array_hx $a
	 * 
	 * @return mixed
	 */
	static public function fromHaxeArray ($a) {
		#/usr/share/haxe/std/php7/NativeIndexedArray.hx:43: characters 2-30
		return $a->arr;
	}


	/**
	 * @param mixed $this
	 * @param int $idx
	 * 
	 * @return mixed
	 */
	static public function get ($this1, $idx) {
		#/usr/share/haxe/std/php7/NativeIndexedArray.hx:31: characters 2-18
		return $this1[$idx];
	}


	/**
	 * @param mixed $this
	 * @param int $idx
	 * @param mixed $val
	 * 
	 * @return mixed
	 */
	static public function set ($this1, $idx, $val) {
		#/usr/share/haxe/std/php7/NativeIndexedArray.hx:35: characters 2-24
		return $this1[$idx] = $val;
	}


	/**
	 * @param mixed $this
	 * 
	 * @return \Array_hx
	 */
	static public function toHaxeArray ($this1) {
		#/usr/share/haxe/std/php7/NativeIndexedArray.hx:39: characters 2-41
		return \Array_hx::wrap($this1);
	}
}


Boot::registerClass(NativeIndexedArray_Impl_::class, 'php._NativeIndexedArray.NativeIndexedArray_Impl_');
