<?php
/**
 * Generated by Haxe 4.0.0
 */

namespace haxe\ds\_HashMap;

use \php\Boot;
use \php\_NativeArray\NativeArrayIterator;

final class HashMap_Impl_ {
	/**
	 * @return HashMapData
	 */
	static public function _new () {
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:35: character 15
		$this1 = new HashMapData();
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:35: character 15
		return $this1;
	}


	/**
	 * @param HashMapData $this
	 * @param mixed $k
	 * 
	 * @return bool
	 */
	static public function exists ($this1, $k) {
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:58: characters 9-41
		$_this = $this1->values;
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:58: characters 9-41
		return array_key_exists($k->hashCode(), $_this->data);
	}


	/**
	 * @param HashMapData $this
	 * @param mixed $k
	 * 
	 * @return mixed
	 */
	static public function get ($this1, $k) {
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:51: characters 9-38
		$_this = $this1->values;
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:51: characters 9-38
		$key = $k->hashCode();
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:51: characters 9-38
		return ($_this->data[$key] ?? null);
	}


	/**
	 * @param HashMapData $this
	 * 
	 * @return object
	 */
	static public function iterator ($this1) {
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:80: characters 9-31
		return new NativeArrayIterator(array_values($this1->values->data));
	}


	/**
	 * @param HashMapData $this
	 * 
	 * @return object
	 */
	static public function keys ($this1) {
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:73: characters 9-29
		return new NativeArrayIterator(array_values($this1->keys->data));
	}


	/**
	 * @param HashMapData $this
	 * @param mixed $k
	 * 
	 * @return bool
	 */
	static public function remove ($this1, $k) {
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:65: characters 2-34
		$this1->values->remove($k->hashCode());
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:66: characters 2-39
		return $this1->keys->remove($k->hashCode());
	}


	/**
	 * @param HashMapData $this
	 * @param mixed $k
	 * @param mixed $v
	 * 
	 * @return void
	 */
	static public function set ($this1, $k, $v) {
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:43: characters 2-32
		$_this = $this1->keys;
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:43: characters 2-32
		$key = $k->hashCode();
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:43: characters 2-32
		$_this->data[$key] = $k;

		#/usr/share/haxe/std/haxe/ds/HashMap.hx:44: characters 2-34
		$_this1 = $this1->values;
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:44: characters 2-34
		$key1 = $k->hashCode();
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:44: characters 2-34
		$_this1->data[$key1] = $v;

	}
}


Boot::registerClass(HashMap_Impl_::class, 'haxe.ds._HashMap.HashMap_Impl_');
