<?php
/**
 * Generated by Haxe 4.0.0
 */

namespace haxe\ds\_HashMap;

use \php\Boot;
use \haxe\ds\IntMap;

class HashMapData {
	/**
	 * @var IntMap
	 */
	public $keys;
	/**
	 * @var IntMap
	 */
	public $values;


	/**
	 * @return void
	 */
	public function __construct () {
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:88: characters 2-21
		$this->keys = new IntMap();
		#/usr/share/haxe/std/haxe/ds/HashMap.hx:89: characters 2-23
		$this->values = new IntMap();
	}
}


Boot::registerClass(HashMapData::class, 'haxe.ds._HashMap.HashMapData');
