<?php
/**
 * Generated by Haxe 4.0.0
 */

use \_Array\ArrayIterator;
use \php\_Boot\HxException;
use \php\Boot;
use \haxe\CallStack;

final class Array_hx implements \ArrayAccess {
	/**
	 * @var mixed
	 */
	public $arr;
	/**
	 * @var int
	 */
	public $length;


	/**
	 * @param mixed $arr
	 * 
	 * @return Array_hx
	 */
	static public function wrap ($arr) {
		#/usr/share/haxe/std/php7/_std/Array.hx:201: characters 2-22
		$a = new Array_hx();
		#/usr/share/haxe/std/php7/_std/Array.hx:202: characters 2-13
		$a->arr = $arr;
		#/usr/share/haxe/std/php7/_std/Array.hx:203: characters 2-30
		$a->length = count($arr);
		#/usr/share/haxe/std/php7/_std/Array.hx:204: characters 2-10
		return $a;
	}


	/**
	 * @return void
	 */
	public function __construct () {
		#/usr/share/haxe/std/php7/_std/Array.hx:33: characters 8-35
		$this1 = [];
		#/usr/share/haxe/std/php7/_std/Array.hx:33: characters 2-35
		$this->arr = $this1;
		#/usr/share/haxe/std/php7/_std/Array.hx:34: characters 2-12
		$this->length = 0;
	}


	/**
	 * @param Array_hx $a
	 * 
	 * @return Array_hx
	 */
	public function concat ($a) {
		#/usr/share/haxe/std/php7/_std/Array.hx:38: characters 2-45
		return Array_hx::wrap(array_merge($this->arr, $a->arr));
	}


	/**
	 * @return Array_hx
	 */
	public function copy () {
		#/usr/share/haxe/std/php7/_std/Array.hx:42: characters 2-18
		return Array_hx::wrap($this->arr);
	}


	/**
	 * @param \Closure $f
	 * 
	 * @return Array_hx
	 */
	public function filter ($f) {
		#/usr/share/haxe/std/php7/_std/Array.hx:46: characters 2-63
		return Array_hx::wrap(array_values(array_filter($this->arr, $f)));
	}


	/**
	 * @param mixed $x
	 * @param int $fromIndex
	 * 
	 * @return int
	 */
	public function indexOf ($x, $fromIndex = null) {
		#/usr/share/haxe/std/php7/_std/Array.hx:50: lines 50-57
		if ($fromIndex === null) {
			#/usr/share/haxe/std/php7/_std/Array.hx:51: characters 3-49
			$index = array_search($x, $this->arr, true);
			#/usr/share/haxe/std/php7/_std/Array.hx:52: lines 52-56
			if ($index === false) {
				#/usr/share/haxe/std/php7/_std/Array.hx:53: characters 4-13
				return -1;
			} else {
				#/usr/share/haxe/std/php7/_std/Array.hx:55: characters 4-16
				return $index;
			}
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:58: characters 2-40
		if ($fromIndex < 0) {
			#/usr/share/haxe/std/php7/_std/Array.hx:58: characters 21-40
			$fromIndex = $fromIndex + $this->length;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:59: characters 2-34
		if ($fromIndex < 0) {
			#/usr/share/haxe/std/php7/_std/Array.hx:59: characters 21-34
			$fromIndex = 0;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:60: lines 60-64
		while ($fromIndex < $this->length) {
			#/usr/share/haxe/std/php7/_std/Array.hx:61: lines 61-62
			if (Boot::equal($this->arr[$fromIndex], $x)) {
				#/usr/share/haxe/std/php7/_std/Array.hx:62: characters 4-20
				return $fromIndex;
			}
			#/usr/share/haxe/std/php7/_std/Array.hx:63: characters 3-14
			$fromIndex = $fromIndex + 1;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:65: characters 2-11
		return -1;
	}


	/**
	 * @param int $pos
	 * @param mixed $x
	 * 
	 * @return void
	 */
	public function insert ($pos, $x) {
		#/usr/share/haxe/std/php7/_std/Array.hx:69: characters 2-10
		$this->length++;
		#/usr/share/haxe/std/php7/_std/Array.hx:70: characters 2-55
		array_splice($this->arr, $pos, 0, [$x]);
	}


	/**
	 * @return object
	 */
	public function iterator () {
		#/usr/share/haxe/std/php7/_std/Array.hx:75: characters 2-32
		return new ArrayIterator($this);
	}


	/**
	 * @param string $sep
	 * 
	 * @return string
	 */
	public function join ($sep) {
		#/usr/share/haxe/std/php7/_std/Array.hx:79: characters 2-61
		return implode($sep, array_map("strval", $this->arr));
	}


	/**
	 * @param mixed $x
	 * @param int $fromIndex
	 * 
	 * @return int
	 */
	public function lastIndexOf ($x, $fromIndex = null) {
		#/usr/share/haxe/std/php7/_std/Array.hx:83: characters 2-70
		if (($fromIndex === null) || ($fromIndex >= $this->length)) {
			#/usr/share/haxe/std/php7/_std/Array.hx:83: characters 48-70
			$fromIndex = $this->length - 1;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:84: characters 2-40
		if ($fromIndex < 0) {
			#/usr/share/haxe/std/php7/_std/Array.hx:84: characters 21-40
			$fromIndex = $fromIndex + $this->length;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:85: lines 85-89
		while ($fromIndex >= 0) {
			#/usr/share/haxe/std/php7/_std/Array.hx:86: lines 86-87
			if (Boot::equal($this->arr[$fromIndex], $x)) {
				#/usr/share/haxe/std/php7/_std/Array.hx:87: characters 4-20
				return $fromIndex;
			}
			#/usr/share/haxe/std/php7/_std/Array.hx:88: characters 3-14
			$fromIndex = $fromIndex - 1;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:90: characters 2-11
		return -1;
	}


	/**
	 * @param \Closure $f
	 * 
	 * @return Array_hx
	 */
	public function map ($f) {
		#/usr/share/haxe/std/php7/_std/Array.hx:94: characters 2-34
		$result = [];
		#/usr/share/haxe/std/php7/_std/Array.hx:95: lines 95-97
		$_g1 = 0;
		#/usr/share/haxe/std/php7/_std/Array.hx:95: lines 95-97
		$_g = $this->length;
		#/usr/share/haxe/std/php7/_std/Array.hx:95: lines 95-97
		while ($_g1 < $_g) {
			#/usr/share/haxe/std/php7/_std/Array.hx:95: lines 95-97
			$_g1 = $_g1 + 1;
			#/usr/share/haxe/std/php7/_std/Array.hx:95: characters 6-7
			$i = $_g1 - 1;
			#/usr/share/haxe/std/php7/_std/Array.hx:96: characters 3-24
			$result[$i] = $f($this->arr[$i]);
		}

		#/usr/share/haxe/std/php7/_std/Array.hx:98: characters 2-21
		return Array_hx::wrap($result);
	}


	/**
	 * @param int $offset
	 * 
	 * @return bool
	 */
	public function offsetExists ($offset) {
		#/usr/share/haxe/std/php7/_std/Array.hx:171: characters 2-24
		return $offset < $this->length;
	}


	/**
	 * @param int $offset
	 * 
	 * @return mixed
	 */
	public function &offsetGet ($offset) {
		#/usr/share/haxe/std/php7/_std/Array.hx:176: lines 176-180
		try {
			#/usr/share/haxe/std/php7/_std/Array.hx:177: characters 10-21
			return $this->arr[$offset];
		} catch (\Throwable $__hx__caught_e) {
			CallStack::saveExceptionTrace($__hx__caught_e);
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/usr/share/haxe/std/php7/_std/Array.hx:179: characters 3-14
			return null;
		}
	}


	/**
	 * @param int $offset
	 * @param mixed $value
	 * 
	 * @return void
	 */
	public function offsetSet ($offset, $value) {
		#/usr/share/haxe/std/php7/_std/Array.hx:185: lines 185-188
		if ($this->length <= $offset) {
			#/usr/share/haxe/std/php7/_std/Array.hx:186: characters 3-81
			$this->arr = array_merge($this->arr, array_fill(0, $offset + 1 - $this->length, null));
			#/usr/share/haxe/std/php7/_std/Array.hx:187: characters 3-22
			$this->length = $offset + 1;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:189: characters 2-21
		$this->arr[$offset] = $value;
	}


	/**
	 * @param int $offset
	 * 
	 * @return void
	 */
	public function offsetUnset ($offset) {
		#/usr/share/haxe/std/php7/_std/Array.hx:194: lines 194-197
		if (($offset >= 0) && ($offset < $this->length)) {
			#/usr/share/haxe/std/php7/_std/Array.hx:195: characters 3-38
			array_splice($this->arr, $offset, 1);
			#/usr/share/haxe/std/php7/_std/Array.hx:196: characters 3-11
			--$this->length;
		}
	}


	/**
	 * @return mixed
	 */
	public function pop () {
		#/usr/share/haxe/std/php7/_std/Array.hx:102: characters 2-26
		if ($this->length > 0) {
			#/usr/share/haxe/std/php7/_std/Array.hx:102: characters 18-26
			$this->length--;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:103: characters 2-30
		return array_pop($this->arr);
	}


	/**
	 * @param mixed $x
	 * 
	 * @return int
	 */
	public function push ($x) {
		#/usr/share/haxe/std/php7/_std/Array.hx:107: characters 2-17
		$this->arr[$this->length] = $x;
		#/usr/share/haxe/std/php7/_std/Array.hx:108: characters 2-17
		return ++$this->length;
	}


	/**
	 * @param mixed $x
	 * 
	 * @return bool
	 */
	public function remove ($x) {
		#/usr/share/haxe/std/php7/_std/Array.hx:112: lines 112-118
		$_g1 = 0;
		#/usr/share/haxe/std/php7/_std/Array.hx:112: lines 112-118
		$_g = $this->length;
		#/usr/share/haxe/std/php7/_std/Array.hx:112: lines 112-118
		while ($_g1 < $_g) {
			#/usr/share/haxe/std/php7/_std/Array.hx:112: lines 112-118
			$_g1 = $_g1 + 1;
			#/usr/share/haxe/std/php7/_std/Array.hx:112: characters 7-8
			$i = $_g1 - 1;
			#/usr/share/haxe/std/php7/_std/Array.hx:113: lines 113-117
			if (Boot::equal($this->arr[$i], $x)) {
				#/usr/share/haxe/std/php7/_std/Array.hx:114: characters 4-34
				array_splice($this->arr, $i, 1);
				#/usr/share/haxe/std/php7/_std/Array.hx:115: characters 4-12
				$this->length--;
				#/usr/share/haxe/std/php7/_std/Array.hx:116: characters 4-15
				return true;
			}
		}

		#/usr/share/haxe/std/php7/_std/Array.hx:119: characters 2-14
		return false;
	}


	/**
	 * @return void
	 */
	public function reverse () {
		#/usr/share/haxe/std/php7/_std/Array.hx:123: characters 2-33
		$this->arr = array_reverse($this->arr);
	}


	/**
	 * @return mixed
	 */
	public function shift () {
		#/usr/share/haxe/std/php7/_std/Array.hx:127: characters 2-26
		if ($this->length > 0) {
			#/usr/share/haxe/std/php7/_std/Array.hx:127: characters 18-26
			$this->length--;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:128: characters 2-32
		return array_shift($this->arr);
	}


	/**
	 * @param int $pos
	 * @param int $end
	 * 
	 * @return Array_hx
	 */
	public function slice ($pos, $end = null) {
		#/usr/share/haxe/std/php7/_std/Array.hx:132: characters 2-28
		if ($pos < 0) {
			#/usr/share/haxe/std/php7/_std/Array.hx:132: characters 15-28
			$pos = $pos + $this->length;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:133: characters 2-22
		if ($pos < 0) {
			#/usr/share/haxe/std/php7/_std/Array.hx:133: characters 15-22
			$pos = 0;
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:134: lines 134-143
		if ($end === null) {
			#/usr/share/haxe/std/php7/_std/Array.hx:135: characters 3-44
			return Array_hx::wrap(array_slice($this->arr, $pos));
		} else {
			#/usr/share/haxe/std/php7/_std/Array.hx:137: characters 3-29
			if ($end < 0) {
				#/usr/share/haxe/std/php7/_std/Array.hx:137: characters 16-29
				$end = $end + $this->length;
			}
			#/usr/share/haxe/std/php7/_std/Array.hx:138: lines 138-142
			if ($end <= $pos) {
				#/usr/share/haxe/std/php7/_std/Array.hx:139: characters 4-13
				return new Array_hx();
			} else {
				#/usr/share/haxe/std/php7/_std/Array.hx:141: characters 4-56
				return Array_hx::wrap(array_slice($this->arr, $pos, $end - $pos));
			}
		}
	}


	/**
	 * @param \Closure $f
	 * 
	 * @return void
	 */
	public function sort ($f) {
		#/usr/share/haxe/std/php7/_std/Array.hx:147: characters 2-14
		usort($this->arr, $f);
	}


	/**
	 * @param int $pos
	 * @param int $len
	 * 
	 * @return Array_hx
	 */
	public function splice ($pos, $len) {
		#/usr/share/haxe/std/php7/_std/Array.hx:151: characters 2-24
		if ($len < 0) {
			#/usr/share/haxe/std/php7/_std/Array.hx:151: characters 15-24
			return new Array_hx();
		}
		#/usr/share/haxe/std/php7/_std/Array.hx:152: characters 2-56
		$result = Array_hx::wrap(array_splice($this->arr, $pos, $len));
		#/usr/share/haxe/std/php7/_std/Array.hx:153: characters 2-8
		$tmp = $this;
		#/usr/share/haxe/std/php7/_std/Array.hx:153: characters 2-25
		$tmp->length = $tmp->length - $result->length;
		#/usr/share/haxe/std/php7/_std/Array.hx:154: characters 2-15
		return $result;
	}


	/**
	 * @return string
	 */
	public function toString () {
		#/usr/share/haxe/std/php7/_std/Array.hx:162: characters 2-35
		$strings = [];
		#/usr/share/haxe/std/php7/_std/Array.hx:163: lines 163-165
		foreach (($this->arr) as $index => $value) {
			#/usr/share/haxe/std/php7/_std/Array.hx:164: characters 3-41
			$val = Boot::stringify($value);
			#/usr/share/haxe/std/php7/_std/Array.hx:164: characters 3-41
			$strings[$index] = $val;
		};
		#/usr/share/haxe/std/php7/_std/Array.hx:166: characters 2-49
		return "[" . (implode(",", $strings)??'null') . "]";
	}


	/**
	 * @param mixed $x
	 * 
	 * @return void
	 */
	public function unshift ($x) {
		#/usr/share/haxe/std/php7/_std/Array.hx:158: characters 2-39
		$this->length = array_unshift($this->arr, $x);
	}


	public function __toString() {
		return $this->toString();
	}
}


Boot::registerClass(Array_hx::class, 'Array');
