<?php
/**
 * Generated by Haxe 4.0.0
 */

use \php\Boot;
use \php\_Boot\HxEnum;

class ValueType extends HxEnum {
	/**
	 * @return ValueType
	 */
	static public function TBool () {
		return HxEnum::singleton(static::class, 'TBool', 3);
	}


	/**
	 * @param Class $c
	 * 
	 * @return ValueType
	 */
	static public function TClass ($c) {
		return new ValueType('TClass', 6, [$c]);
	}


	/**
	 * @param Enum $e
	 * 
	 * @return ValueType
	 */
	static public function TEnum ($e) {
		return new ValueType('TEnum', 7, [$e]);
	}


	/**
	 * @return ValueType
	 */
	static public function TFloat () {
		return HxEnum::singleton(static::class, 'TFloat', 2);
	}


	/**
	 * @return ValueType
	 */
	static public function TFunction () {
		return HxEnum::singleton(static::class, 'TFunction', 5);
	}


	/**
	 * @return ValueType
	 */
	static public function TInt () {
		return HxEnum::singleton(static::class, 'TInt', 1);
	}


	/**
	 * @return ValueType
	 */
	static public function TNull () {
		return HxEnum::singleton(static::class, 'TNull', 0);
	}


	/**
	 * @return ValueType
	 */
	static public function TObject () {
		return HxEnum::singleton(static::class, 'TObject', 4);
	}


	/**
	 * @return ValueType
	 */
	static public function TUnknown () {
		return HxEnum::singleton(static::class, 'TUnknown', 8);
	}


	/**
	 * Returns array of (constructorIndex => constructorName)
	 *
	 * @return string[]
	 */
	static public function __hx__list () {
		return [
			3 => 'TBool',
			6 => 'TClass',
			7 => 'TEnum',
			2 => 'TFloat',
			5 => 'TFunction',
			1 => 'TInt',
			0 => 'TNull',
			4 => 'TObject',
			8 => 'TUnknown',
		];
	}


	/**
	 * Returns array of (constructorName => parametersCount)
	 *
	 * @return int[]
	 */
	static public function __hx__paramsCount () {
		return [
			'TBool' => 0,
			'TClass' => 1,
			'TEnum' => 1,
			'TFloat' => 0,
			'TFunction' => 0,
			'TInt' => 0,
			'TNull' => 0,
			'TObject' => 0,
			'TUnknown' => 0,
		];
	}
}


Boot::registerClass(ValueType::class, 'ValueType');
