<?php
/**
 * Generated by Haxe 4.0.0
 */

namespace php\_NativeArray;

use \php\Boot;

class NativeArrayIterator {
	/**
	 * @var mixed
	 */
	public $arr;
	/**
	 * @var bool
	 */
	public $hasMore;


	/**
	 * @param mixed $a
	 * 
	 * @return void
	 */
	public function __construct ($a) {
		#/usr/share/haxe/std/php7/NativeArray.hx:54: characters 2-9
		$this->arr = $a;
		#/usr/share/haxe/std/php7/NativeArray.hx:55: characters 2-34
		$this->hasMore = reset($this->arr) !== false;
	}


	/**
	 * @return bool
	 */
	public function hasNext () {
		#/usr/share/haxe/std/php7/NativeArray.hx:59: characters 2-16
		return $this->hasMore;
	}


	/**
	 * @return mixed
	 */
	public function next () {
		#/usr/share/haxe/std/php7/NativeArray.hx:63: characters 2-29
		$result = current($this->arr);
		#/usr/share/haxe/std/php7/NativeArray.hx:64: characters 2-33
		$this->hasMore = next($this->arr) !== false;
		#/usr/share/haxe/std/php7/NativeArray.hx:65: characters 2-15
		return $result;
	}
}


Boot::registerClass(NativeArrayIterator::class, 'php._NativeArray.NativeArrayIterator');
