<?php
/**
 * Generated by Haxe 4.0.0
 */

namespace php\_Boot;

use \php\Boot;

class HxAnon extends \StdClass {
	/**
	 * @param mixed $fields
	 * 
	 * @return void
	 */
	public function __construct ($fields = null) {
		#/usr/share/haxe/std/php7/Boot.hx:774: lines 774-779
		$_gthis = $this;
		#/usr/share/haxe/std/php7/Boot.hx:775: characters 2-9
		;
		#/usr/share/haxe/std/php7/Boot.hx:776: lines 776-778
		if ($fields !== null) {
			#/usr/share/haxe/std/php7/Boot.hx:777: characters 3-83
			foreach ($fields as $name => $value) {
				#/usr/share/haxe/std/php7/Boot.hx:777: characters 64-68
				$tmp = $_gthis;
				#/usr/share/haxe/std/php7/Boot.hx:777: characters 70-74
				$tmp1 = $name;
				#/usr/share/haxe/std/php7/Boot.hx:777: characters 48-82
				$tmp->{$tmp1} = $value;
			};
		}
	}


	/**
	 * @param string $name
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	public function __call ($name, $args) {
		#/usr/share/haxe/std/php7/Boot.hx:788: characters 31-35
		$tmp = $this;
		#/usr/share/haxe/std/php7/Boot.hx:788: characters 37-41
		$tmp1 = $name;
		#/usr/share/haxe/std/php7/Boot.hx:788: characters 2-43
		$method = $tmp->{$tmp1};
		#/usr/share/haxe/std/php7/Boot.hx:789: characters 2-24
		;
		#/usr/share/haxe/std/php7/Boot.hx:790: characters 2-35
		return $method(...$args);
	}


	/**
	 * @param string $name
	 * 
	 * @return mixed
	 */
	public function __get ($name) {
		#/usr/share/haxe/std/php7/Boot.hx:783: characters 2-13
		return null;
	}
}


Boot::registerClass(HxAnon::class, 'php._Boot.HxAnon');
