<?php
/**
 * Generated by Haxe 4.0.0
 */

namespace php\_NativeAssocArray;

use \php\Boot;

final class NativeAssocArray_Impl_ {
	/**
	 * @return mixed
	 */
	static public function _new () {
		#/usr/share/haxe/std/php7/NativeAssocArray.hx:26: character 15
		$this1 = [];
		#/usr/share/haxe/std/php7/NativeAssocArray.hx:26: character 15
		return $this1;
	}


	/**
	 * @param mixed $this
	 * @param string $key
	 * 
	 * @return mixed
	 */
	static public function get ($this1, $key) {
		#/usr/share/haxe/std/php7/NativeAssocArray.hx:31: characters 2-18
		return $this1[$key];
	}


	/**
	 * @param mixed $this
	 * @param string $key
	 * @param mixed $val
	 * 
	 * @return mixed
	 */
	static public function set ($this1, $key, $val) {
		#/usr/share/haxe/std/php7/NativeAssocArray.hx:35: characters 2-24
		return $this1[$key] = $val;
	}
}


Boot::registerClass(NativeAssocArray_Impl_::class, 'php._NativeAssocArray.NativeAssocArray_Impl_');
