<?php
/**
 * Generated by Haxe 4.0.0
 */

namespace _Map;

use \haxe\IMap;
use \haxe\ds\StringMap;
use \php\Boot;
use \haxe\ds\EnumValueMap;
use \haxe\ds\ObjectMap;
use \haxe\ds\IntMap;

final class Map_Impl_ {
	/**
	 * @param IMap $this
	 * @param mixed $k
	 * @param mixed $v
	 * 
	 * @return mixed
	 */
	static public function arrayWrite ($this1, $k, $v) {
		#/usr/share/haxe/std/Map.hx:135: characters 2-16
		$this1->set($k, $v);
		#/usr/share/haxe/std/Map.hx:136: characters 2-10
		return $v;
	}


	/**
	 * @param IMap $this
	 * @param mixed $key
	 * 
	 * @return bool
	 */
	static public function exists ($this1, $key) {
		#/usr/share/haxe/std/Map.hx:97: characters 38-61
		return $this1->exists($key);
	}


	/**
	 * @param IntMap $map
	 * 
	 * @return IntMap
	 */
	static public function fromIntMap ($map) {
		#/usr/share/haxe/std/Map.hx:160: characters 2-17
		return $map;
	}


	/**
	 * @param ObjectMap $map
	 * 
	 * @return ObjectMap
	 */
	static public function fromObjectMap ($map) {
		#/usr/share/haxe/std/Map.hx:164: characters 2-17
		return $map;
	}


	/**
	 * @param StringMap $map
	 * 
	 * @return StringMap
	 */
	static public function fromStringMap ($map) {
		#/usr/share/haxe/std/Map.hx:156: characters 2-17
		return $map;
	}


	/**
	 * @param IMap $this
	 * @param mixed $key
	 * 
	 * @return mixed
	 */
	static public function get ($this1, $key) {
		#/usr/share/haxe/std/Map.hx:90: characters 49-69
		return $this1->get($key);
	}


	/**
	 * @param IMap $this
	 * 
	 * @return object
	 */
	static public function iterator ($this1) {
		#/usr/share/haxe/std/Map.hx:122: characters 2-24
		return $this1->iterator();
	}


	/**
	 * @param IMap $this
	 * 
	 * @return object
	 */
	static public function keys ($this1) {
		#/usr/share/haxe/std/Map.hx:113: characters 2-20
		return $this1->keys();
	}


	/**
	 * @param IMap $this
	 * @param mixed $key
	 * 
	 * @return bool
	 */
	static public function remove ($this1, $key) {
		#/usr/share/haxe/std/Map.hx:105: characters 38-61
		return $this1->remove($key);
	}


	/**
	 * @param IMap $this
	 * @param mixed $key
	 * @param mixed $value
	 * 
	 * @return void
	 */
	static public function set ($this1, $key, $value) {
		#/usr/share/haxe/std/Map.hx:73: characters 44-64
		$this1->set($key, $value);
	}


	/**
	 * @param IMap $t
	 * 
	 * @return EnumValueMap
	 */
	static public function toEnumValueMapMap ($t) {
		#/usr/share/haxe/std/Map.hx:148: characters 2-33
		return new EnumValueMap();
	}


	/**
	 * @param IMap $t
	 * 
	 * @return IntMap
	 */
	static public function toIntMap ($t) {
		#/usr/share/haxe/std/Map.hx:144: characters 2-24
		return new IntMap();
	}


	/**
	 * @param IMap $t
	 * 
	 * @return ObjectMap
	 */
	static public function toObjectMap ($t) {
		#/usr/share/haxe/std/Map.hx:152: characters 2-30
		return new ObjectMap();
	}


	/**
	 * @param IMap $this
	 * 
	 * @return string
	 */
	static public function toString ($this1) {
		#/usr/share/haxe/std/Map.hx:131: characters 2-24
		return $this1->toString();
	}


	/**
	 * @param IMap $t
	 * 
	 * @return StringMap
	 */
	static public function toStringMap ($t) {
		#/usr/share/haxe/std/Map.hx:140: characters 2-27
		return new StringMap();
	}
}


Boot::registerClass(Map_Impl_::class, '_Map.Map_Impl_');
